### ISSUE TITLE
create and post materials for Part I

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#1]

**Comment by nicholasjhorton** [comment]
I've posted the materials for part I.  There are some space issues and warnings that still need to be addressed but this is coming together nicely.  @mchien20 can you please review the pdfs and update as needed?

**Comment by nicholasjhorton** [comment]
Need additional page numbers and figure numbers throughout.

**Comment by nicholasjhorton** [comment]
@mchien20 this is coming along nicely (and I've pushed commits: see https://github.com/Amherst-Statistics/IS5inR/commit/a003431942dea053614415b51457bc47af249fd7) and updated the website.  Can you please review and let me know if you see issues or have questions?

**Comment by shukryzablah** [comment]
done and posted
