### ISSUE TITLE
update website (like what Sarah did for SDM4)

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#11]

**Comment by mchien20** [comment]
updated the files; not sure if the pointers need to be updated because they should have the same file names, they're just not created yet

**Comment by nicholasjhorton** [comment]
Thanks.  In future can you please include the link to the commit to make it easier for me to review your changes?

**Comment by nicholasjhorton** [comment]
I published these changes: these look great, thanks!
