### ISSUE TITLE
chapter 14 annotation

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#17]
We need to add more description of what is happening: e.g., "do() * mean(, data = sample(ds, 100))" is repeatedly taking samples of size 100 from a known population to estimate the sampling distribution.  

Our goal here is to make these materials mostly accessible to instructors without access to the book (as an additional resource for their teaching).  

We don't need a full-blown analysis but some additional guidance would be helpful for this and other chapters.

**Comment by nicholasjhorton** [comment]
See https://github.com/Amherst-Statistics/IS5inR/commit/c650788d07f16651e7ce464cc4befbc904d20467 for more queries...

**Comment by mchien20** [comment]
I added some here: https://github.com/Amherst-Statistics/IS5inR/commit/f2095cf00b775ac2e7daef98f699ad046408c4c0
Let me know if that sentence is enough.

**Comment by mchien20** [comment]
I added some here: https://github.com/Amherst-Statistics/IS5inR/commit/77aff8125338453cd31de33a15fa999d73bf8450

**Comment by nicholasjhorton** [comment]
Chapter 14 is shaping up well.  Can you please review these changes (https://github.com/Amherst-Statistics/IS5inR/commit/591a15d4a5d08eb93e4d7d6494038e719a5ef9cf)?  In particular we'll always want to name arguments (i.e., when setting a sample size in `sample()`).  And it's important to be careful with figure captions ("Mean" isn't very helpful: sample?  population?  resample?).

Can you please add one more figure that displays the sampling distribution of the mean using overlapping density plots?

**Comment by nicholasjhorton** [comment]
One additional request: can you please label the t/normal plot (Figure 14.9, page 446) by adding names on the figure near the curves?

**Comment by nicholasjhorton** [comment]
I'm just reviewing section 14.1.  You'll need to add the calculations using `xpt()` to example 14.1 (page 448).  It's good to also compare this to the results from `confint(lm())`.  In addition, you'll want to overlay a normal density on top of the histogram of the values for 14.2.

**Comment by mchien20** [comment]
Made edits: https://github.com/Amherst-Statistics/IS5inR/commit/29c06bb21248b9ff3c3e88891795cab55c7733bb

**Comment by nicholasjhorton** [comment]
This figure needs a legend (and text annotation after the figure).
<img width="630" alt="screen shot 2018-07-16 at 5 04 39 pm" src="https://user-images.githubusercontent.com/530542/42789495-6e2f3f5e-891a-11e8-86d1-f683e6916a20.png">

**Comment by mchien20** [comment]
Fixed: https://github.com/Amherst-Statistics/IS5inR/commit/4f4a19b52599c2f33ea722748670d1a36ee04fc7
