### ISSUE TITLE
Need full baby dataset to replicate fig14.10 and 14.11 (or do it for the employee commute times p.455-456)

### ISSUE THREAD

**Issue by mchien20** [Amherst-Statistics/IS5inR#18]
In Chapter 14, there are two instances in which a 95% confidence interval is found for bootstrap means.
Figure 14.11 (page 455):
library(mosaic)
library(readr)
library(janitor)
Babies <- read_csv("http://nhorton.people.amherst.edu/is5/data/Babysamp_98.csv") %>%
  clean_names()
set.seed(1243536)
numsim <- 10000
bootstrapmeans <- do(numsim) * mean(~ weight, data = mosaic::resample(Babies, 100)) 
gf_histogram(~ mean, data = bootstrapmeans) %>%
  gf_labs(x = "Bootstrap Means", y = "")
# Figure 14.11
bootstraplm <- lm(mean ~ 1, data = bootstrapmeans)
confint(bootstraplm) 

Example (page 456):
Commute <- read_csv("http://nhorton.people.amherst.edu/is5/data/Population_Commute_Times.csv") %>%
  clean_names()
set.seed(134)
numsim <- 10000
commutebootstrap <- do(numsim) * mean(~ commute_time, data = mosaic::resample(Commute, 100))
gf_histogram(~ mean, data = commutebootstrap, title = "Time Bootstrap Set Means") %>%
  gf_labs(x = "", y = "")
cbootlm <- lm(mean ~ 1, data = commutebootstrap)
confint(cbootlm)

I've tried both confint() and t.test(), but the intervals are a lot narrower than the ones in the book. I tried multiple seeds, but they were all similar.

**Comment by nicholasjhorton** [comment]
I don’t have access to the book but wonder why samples of size 100 are taken here. Is this still a hypothetical sampling distribution or is the goal to bootstrap an interval?

All the best,

Nick

**Comment by mchien20** [comment]
Both are sampling and finding the mean each time. Then a 95% confidence interval is constructed of those means. The book uses samples of size 100

**Comment by nicholasjhorton** [comment]
Can the three of you review this section of the book prior to our meeting?  Something doesn’t sound right here. 

All the best,

Nick

**Comment by amywagaman** [comment]
Nick, this looks to be because the previous discussions involved simulating a sampling distribution based on samples of size 100. So, they continue to just use a random sample of size 100 as their basis for everything they are bootstrapping. They basically pretend they don’t have access to the entire data set.

So, basically, it should be draw a random sample of size 100, then bootstrap a CI for the mean birthweight using just those 100 observations.

Does that help?
Amy

**Comment by mchien20** [comment]
I've discussed this with both Bonnie and Shukry, but it seems like Bonnie has the same problem of the confidence intervals not matching.

**Comment by mchien20** [comment]
Deleted code related to babies example: https://github.com/Amherst-Statistics/IS5inR/commit/7cd527fdb9f5805ea4a8715d6f7e74e8b51b53d1
