### ISSUE TITLE
Partial Regression Models

### ISSUE THREAD

**Issue by mchien20** [Amherst-Statistics/IS5inR#19]
Not sure how to plot the partial regression plot in Chapter 9, page 286.

**Comment by amywagaman** [comment]
Margaret,

If it helps, partial regression plots are the same thing as added variable plots from stat 230. We had a function that made them for us in class, but the concept is that you just need the appropriate two sets of residuals to plot in their own scatterplot.

And the I() part for the other issue is in Stat2 as well. Good luck!

ASW

**Comment by mchien20** [comment]
https://github.com/Amherst-Statistics/IS5inR/commit/f2095cf00b775ac2e7daef98f699ad046408c4c0
