### ISSUE TITLE
create and post materials for Part II

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#2]

**Comment by mchien20** [comment]
Rmds are ready to post: https://github.com/Amherst-Statistics/IS5inR/commit/b7eaa9ef2718d979a0e662be32b4258e4eae1ffb

**Comment by nicholasjhorton** [comment]
While these chapters are awaiting one final review by @shukryzablah and @bonnfire I will be reposting them and closing this issue.
