### ISSUE TITLE
Error in Linear Model

### ISSUE THREAD

**Issue by mchien20** [Amherst-Statistics/IS5inR#20]
library(mosaic)
library(readr)
DirtBikes <- read_csv("http://nhorton.people.amherst.edu/is5/data/Dirt_bikes_2014.csv")
DirtBikes <- DirtBikes %>%
  filter(Cooling != "NA") %>%
  mutate(Cooling = ifelse(Cooling == "Air-Cooled", "Air-Cooled", "LiquidCooled"))
gf_point(MSRP ~ (Displacement)^(1/3), color = ~ Cooling, data = DirtBikes) %>%
  gf_lm()
bikeslm <- lm(MSRP ~ Displacement^(1/3) + Cooling, data = DirtBikes)

The last line of code gives me an error: Error in terms.formula(formula, data = data) : invalid power in formula
I understand that it's because of Displacement^(1/3), but I'm not sure how to get around it.
(Chapter 9, page 291)

**Comment by nicholasjhorton** [comment]
Try enclosing that term with the I() function. See ?I   (Capital i) for details and examples. 

All the best,

Nick

**Comment by nicholasjhorton** [comment]
I’m worried about the filter() command. Are these really coded as strings “NA”? I hope not. Using !is.na() would be far preferable if they are coded as NA. 

All the best,

Nick

**Comment by nicholasjhorton** [comment]
Another option would be to generate the transformed variable in the mutate call. That might be my preference as the name would automatically show up in the plot. 

All the best,

Nick
