### ISSUE TITLE
Parallel Slopes Model

### ISSUE THREAD

**Issue by mchien20** [Amherst-Statistics/IS5inR#21]
In Chapter 9, page 294, there's a visualization with parallel slopes and one that isn't. gf_lm() automatically adds the interaction into the model. I looked at Bonnie's code for parallel slopes, but since there are 8 levels, I am looking for a simpler way to do it.
Here's the model:
library(readr)
library(mosaic)
library(janitor)
Diamonds <- read_csv("http://nhorton.people.amherst.edu/is5/data/Diamonds.csv") %>%
  clean_names()
diamondlm <- lm(sqrt(price) ~ carat_size + color, data = Diamonds)
msummary(diamondlm)

**Comment by mchien20** [comment]
I used broom in this commit: https://github.com/Amherst-Statistics/IS5inR/commit/de258ed94866de545c0d297e2d839a2936de21e6
However, I can't seem to get the parallel slopes to work.

**Comment by nicholasjhorton** [comment]
@shukryzablah can you please check in on this front?

**Comment by shukryzablah** [comment]
Is this what we want?: 

``` r
library(readr)
library(mosaic)
library(janitor)
library(broom)
Diamonds <- read_csv(
  "http://nhorton.people.amherst.edu/is5/data/Diamonds.csv"
  ) %>%
  clean_names()
diamondlm <- lm(sqrt(price) ~ carat_size + color, data = Diamonds)

augmentedMod <- augment(diamondlm)

gf_point(sqrt.price. ~ carat_size, data = augmentedMod, color = ~ color) %>%
  gf_line(.fitted ~ carat_size)
```

![](https://i.imgur.com/xAJnzPW.png)

Created on 2018-07-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mchien20** [comment]
https://github.com/Amherst-Statistics/IS5inR/commit/7f804358e45856e9367c6302d91fa8f2bdb0cd14
