### ISSUE TITLE
Page 325 - AllBirths1998 dataset

### ISSUE THREAD

**Issue by mchien20** [Amherst-Statistics/IS5inR#23]
Does not seem to be included on the website

**Comment by nicholasjhorton** [comment]
I tracked this down: please see https://github.com/Amherst-Statistics/IS5inR/blob/master/website/data/AllBirths1998.csv

**Comment by mchien20** [comment]
Can this data be put in the nhorton website?

**Comment by nicholasjhorton** [comment]
I've republished the site.
