### ISSUE TITLE
break code chunks so annotations show up in the correct place

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#24]
@mchien20 can you please replicate this approach in the other chapters (then close this issue)?  Thanks in advance, Nick

https://github.com/Amherst-Statistics/IS5inR/commit/560267454b7118ba72f597d6fa42f0e47ad09534

**Comment by mchien20** [comment]
Fixed: https://github.com/Amherst-Statistics/IS5inR/commit/64b12bc906ba3ab9728007e009d43ad116a2a7d0
