### ISSUE TITLE
Data Needed

### ISSUE THREAD

**Issue by mchien20** [Amherst-Statistics/IS5inR#25]
Chapter 15:
- page 487 - medical data with temperatures of healthy adults
- page 489 step by step example - baseball data from the 2013 season with a variable that shows whether a team is home or away
Chapter 17:
- page 542 - seatbelt data, there seems to be a data set about seatbelts, but it doesn't have the variables or observations the book uses
- page 543 - online profiles data
- page 547 - sleep data
- page 552 - bowl data (not sure if important though)

**Comment by nicholasjhorton** [comment]
Chapter 15:
- page 487 - medical data with temperatures of healthy adults (MY RESPONSE: Isn't this just the Pulse_rates.csv mentioned in exercse 23 on page 464?)
- page 489 step by step example - baseball data from the 2013 season with a variable that shows whether a team is home or away (MY RESPONSE: Please create this dataset (it's just a vector of 1's and 0's).  
Chapter 15
- page 542 - seatbelt data, there seems to be a data set about seatbelts, but it doesn't have the variables or observations the book uses (MY RESPONSE: where is this used?)
- page 543 - online profiles data (MY RESPONSE: this is OK-Cupid, no?)
- page 547 - sleep data (MY RESPONSE: Please create this dataset (it's just a vector of 1's and 0's).  
- page 552 - bowl data (MY RESPONSE: Please just do the calculations using the provided summary statistics.

**Comment by mchien20** [comment]
- page 487: Pulse_rates.csv has one variable: "Pulse"

- seat belt data is talked about starting on page 541 (I mislabelled the chapter it appears in, which is chapter 17) calculations are on page 542, the step-by-step example that begins on page 545, 
- online profiles data is not okcupid. It's about the percentages of teenagers who have online profiles

**Comment by nicholasjhorton** [comment]
I believe that this is resolved (but will defer to @mchien20 )

**Comment by mchien20** [comment]
Currently resolved, if I run into missing data later, this will be reopened.
