### ISSUE TITLE
Chapters 2 + 4 Bonnie's reviews

### ISSUE THREAD

**Issue by bonnfire** [Amherst-Statistics/IS5inR#27]
Since I don't have repo rights to push the changes that I noted, I have included the PDF file (Issues don't accept Rmd files). I have included questions for Margaret and Nick annotated by XX. 
Chapter 2: 
[ch2is5.pdf](https://github.com/Amherst-Statistics/IS5inR/files/2185638/ch2is5.pdf)
Chapter 4: 
[ch4is5.pdf](https://github.com/Amherst-Statistics/IS5inR/files/2185999/ch4is5.pdf)

**Comment by bonnfire** [comment]
Either:
- pull request, fork, change files, push
- send Rmd files to Margaret

**Comment by nicholasjhorton** [comment]
Can you please let me know what commits these were associated with?  We're nearing the end game so I need to approve the changes moving forward.  Thanks in advance, Nick
