### ISSUE TITLE
add link to the data on the IS5 website

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#28]

**Comment by mchien20** [comment]
added: https://github.com/Amherst-Statistics/IS5inR/commit/c36e8f66dfd59e39d063293663a4a8cb3735977a

**Comment by nicholasjhorton** [comment]
@mchien20 note here's a direct link to the data that we provide: (see https://github.com/Amherst-Statistics/IS5inR/commit/a565f8ef5fb16fc06acbb839ef56d9a4fb12c552)  @bonnfire will want to add something like this for IPS9.
