### ISSUE TITLE
need to fix XX in Chapters 2, 4, and 17

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#29]
Chapter02.Rmd:# XX MC Not sure why the bins by the peak are off from textbook
Chapter02.Rmd:# XX MC and NH the y axis not displaying counts seems to be a bug in ggformula that cannot be fixed 
Chapter02.Rmd:# XX BL be consistent with labs in ggformula
Chapter02.Rmd:XX MC Do you want to include Figure 2.15 on page 32 for the 
Chapter04.Rmd:XX MC removed beause we made the same graph earlier

**Comment by nicholasjhorton** [comment]
Yipes: there are commit errors in Chapters 2 and 4:

Chapter02.Rmd:<<<<<<< HEAD
Chapter04.Rmd:<<<<<<< HEAD
Chapter04.Rmd:<<<<<<< HEAD
Chapter04.Rmd:<<<<<<< HEAD

**Comment by mchien20** [comment]
Chapter 2: https://github.com/Amherst-Statistics/IS5inR/commit/fc7c0a519be2a137b1669a83a126cb5779079241
Chapter 4: https://github.com/Amherst-Statistics/IS5inR/commit/ffcf05b14d4bc8eaec0cadf1f6b48db45a1b2186
