### ISSUE TITLE
need to review which figures need to be made larger

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#30]
Some formatting issues ensued when the default figure size was bumped down to 3 high and 5 wide.  I've fixed several in chapter 3 (https://github.com/Amherst-Statistics/IS5inR/commit/923a7d1ba21111e12c937838f7165b2a42d3efc9) see but a general review of all of the other figures in other chapters is needed.

**Comment by mchien20** [comment]
Looked through all the chapters, fixed 9 and 14: https://github.com/Amherst-Statistics/IS5inR/commit/0f6f654be7a233b58f50dbfea01ea6dc153639cd
