### ISSUE TITLE
Bonnie even IS5 reviews 

### ISSUE THREAD

**Issue by bonnfire** [Amherst-Statistics/IS5inR#31]
Ch 6 212f3944c06c735ac4dd307d6c1d585043994b35 (Completed with comments to be reviewed)
Ch 8 (Margaret has reviewed all comments)
Ch 10 N/A
Ch 12 N/A
Ch 14
(code line) (comment)
(59) The histogram doesn't match the one in the textbook. 
(62) Figure 14.2 generation should be in one code chunk to avoid confusion
(88) page number
(89) fix center of histogram
(92, 164, 187) no need to set another seed
(94, 98, 102) vaguely remember that Nick wanted you to change the names of the dataset
(134, 184) code options message = F? and page reference
(150) add line about what xqt is
(170) conf int differs from textbook (3364, 3633)
(178) page reference, center
(196) running this confint line gives me 
Error in stats::binom.test(x = count, n = n, p = p, alternative = alternative, : unused argument (method = "quantile")
****
Ch 16

No comments
****
Ch 18 
(67) either call the package at the top with all of the other packages or do a package::function() call at line 71
(81) Add page number here instead of line 588
(98-102) sudden switch to Dexterity data, consider moving this chunk earlier or later/after you walk us through the Nearly Normal condition for the Workweek data... I'm thinking of either removing it bc it is kind of irrelevant or at the very least move it right after you discuss it
(133) comment what you're doing here to be consistent and explain what xpt() does; point out the diff from the textbook, but also include a note that your graph is more helpful since we're doing a one sided text (unless they are multiplying by 2 to get the two sided p value???)
(139) message=F
(229) just for personal reference, how/where did you specify what ddex is? it doesn't seem to be in DexBoots data? 
****
Ch 20
(96-98) should we be concerned about its non-normal shape
(111, 129, 198, 225) message=F
(119-123) gf_labs()
(129, 212) figure number and page number
(140) try binwidth = 1.5/3?
(160-167) why assign to variable and then display? just run the code and comment what it means 
i.e. (mean- 0.00)/se # t value 
(180) page ref
(191, 193) use msummary ALSO mouthmlm typo, do you want to consider re-naming this model to clarify the diff bw it and the previous model (applies to code 208 too)

**Comment by mchien20** [comment]
https://github.com/Amherst-Statistics/IS5inR/commit/619970cc9eb56ca4c3837cedfbc59a351bce91fa
