### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by mchien20** [Amherst-Statistics/IS5inR#32]
Chapter 18:
- Winter Olympics speed skating 2006 (stepbystep ex on page 589, fig 18.2 on page 594)
- Work week data  (ex 18.3 on page 591, ex 18.4 on page 595)

**Comment by nicholasjhorton** [comment]
Can you please paste in a photo to give me some additional context?  

All the best,

Nick

**Comment by mchien20** [comment]
![img_1983](https://user-images.githubusercontent.com/31358486/42886318-41b96032-8a71-11e8-9679-1f282a200e1e.JPG)

The work week data seems to be in a table that I somehow missed. I'll create that dataset.

**Comment by mchien20** [comment]
Looking again, it seems like the work week data can be used to make a complete example (the book breaks it up into 3 different examples that, together, make a whole step-by-step one). In this case,  the speed skating data may not be necessary.

**Comment by nicholasjhorton** [comment]
I agree.  One example should suffice here.
