### ISSUE TITLE
Shukry odd reviews in IS5

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#33]

**Comment by nicholasjhorton** [comment]
Any issues/problems here that need attention?  Where do things stand with these reviews?

**Comment by shukryzablah** [comment]
## Odd reviews

Gave it a quick read. These chapters are amazing. These modifications aren't that important.

### Chapter 7 

**Smoother** first figure of ch.7
**smoother** in "step by step example calc a regression equation"

### Chapter 9 

Equal variance assumption fig9.4 **add horizontal line**
Fig.9.5 qqplot **add diagonal line**
pg.284 step by step example **add smoothers or horizontal lines**

**Comment by mchien20** [comment]
Addressed: https://github.com/Amherst-Statistics/IS5inR/commit/aab72c2f51066ae25d9081c071b34330f7b3b9cc

**Comment by nicholasjhorton** [comment]
Is this ready to be closed?

**Comment by mchien20** [comment]
I wasn't sure if Shukry reviewed all the chapters or just the ones above. I'll ask.
