### ISSUE TITLE
chapters not compiling

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#35]
Quitting from lines 182-193 (Chapter08.Rmd) 
Error in head(summaryHeightsWeights) : 
  object 'summaryHeightsWeights' not found
Calls: render ... withCallingHandlers -> withVisible -> eval -> eval -> head

Chapter09.Rmd: 

Error: C stack usage  7971168 is too close to the limit

(also, can you please break up these code chunks with lots of different things happening in them?

**Comment by mchien20** [comment]
Fixed Chapter 8 and broke up code chunks in Chapter 9: https://github.com/Amherst-Statistics/IS5inR/commit/b613256a7629287a6fc047fd680303ad14f86c06
