### ISSUE TITLE
Chapter09.Rmd is not compiling

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#37]
label: unnamed-chunk-17
Error: C stack usage  7971136 is too close to the limit

Execution halted

**Comment by shukryzablah** [comment]
Changing this line: 
```
glance(coasterlm2asdata)
```

to this line: 

```
glance(coasterlm2asdata %>% as.data.frame())
```
Ouput:
```
# A tibble: 1 x 4
   nrow  ncol complete.obs na.fraction
  <int> <int>        <int>       <dbl>
1    90    11           90           0
```

solves the issue, allows compilation, but gives deprecation warning: glance.data.frame is deprecated.

This is the justification for this line: `Here we use `names()` to check out the column names and `glance()` to view the structure of the data set.`

I think it's better just to drop the line.

**Comment by nicholasjhorton** [comment]
Fixed via https://github.com/Amherst-Statistics/IS5inR/commit/812e8bb47c95e9adaa1692db6b397604e68d4f2a

(note that glance wants a lm as argument, not a data frame)
