### ISSUE TITLE
publicize materials on the interweb

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#6]

**Comment by nicholasjhorton** [comment]
I'm planning to post the availability of these materials later today (with a tag for #JSM2018)

**Comment by mchien20** [comment]
Issues should have been addressed. Let me know if there's anything else with IS5.

**Comment by nicholasjhorton** [comment]
Done (see https://twitter.com/askdrstats/status/1022539143270813701)
