### ISSUE TITLE
review and post chapter 2

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/IS5inR#8]
I've made some light edits and added some queries for @mchien20 via https://github.com/Amherst-Statistics/IS5inR/commit/88303cdb0c4b418a5353ad9d2e577c70dfc690ec

**Comment by mchien20** [comment]
pushed a final rmd for ch 2
only thing is that the plots could be smaller if we want to save space

**Comment by nicholasjhorton** [comment]
In prior iterations, I spent considerable time and energy making these smaller.  But I'm no longer printing them so let's not worry too much about that.
